export const CREATE_TODO = 'CREATE_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const DONE_TODO = 'DONE_TODO'
export const DELETE_ALL_TODOS = 'DELETE_ALL_TODOS'
export const CREATE_LIST = 'CREATE_LIST'
export const DELETE_LIST = 'DELETE_LIST'
